server:
  port: 9092


eureka:
  client:
    register-with-eureka: false # 本服务是服务消费者 不需要注册到注册中心
    fetch-registry: true #本微服务为服务消费者，需要到服务注册中心搜索服务
    service-url: # Eureka Server地址
      defaultZone: http://eureka9080.com:9080/eureka/,http://eureka9082.com:9082/eureka/,http://eureka9083.com:9083/eureka/  # Eureka Server地址
