server:
  port: 9001

spring:
  application:
    name: cloud-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址

management:
  ednpoints:
    web:
      exposure:
        include: "*"
